services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9004:80"
    volumes:
      - data:/app/data
    labels:
      - "glance.name=Gotify"
      - "glance.icon=si:gotify"
      - "glance.url=https://gotify.lab"
      - "glance.category=core"

volumes:
  data:
