{
 "title": "Sablier",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Currently Active Groups",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(sablier_group_locked)" }
   ]
  },
  {
   "title": "Active Instances per Group",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "sablier_group_active_instances" }
   ]
  },
  {
   "title": "Session Lock Status per Group",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "sablier_group_locked" }
   ]
  }
 ]
}