services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:2.8.0-ultra-lite
    container_name: stirling-pdf
    restart: unless-stopped
    ports:
      - "9016:8080"
    environment:
      - SECURITY_ENABLELOGIN=false
    volumes:
      - ./data:/configs
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:8080/api/v1/info/status"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 10s
    labels:
      - "sablier.enable=true"
      - "sablier.group=stirling-pdf"
      - "glance.name=Stirling PDF"
      - "glance.url=https://stirling-pdf.lab"
      - "glance.category=on-demand"
