services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "8222:80"
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      DOMAIN: https://vaultwarden.lab
      SIGNUPS_ALLOWED: "true"
    volumes:
      - /srv/homelab/vaultwarden:/data
    security_opt:
      - no-new-privileges:true
