services:
  sablier:
    image: sablierapp/sablier:1.18.0
    container_name: sablier
    restart: unless-stopped
    command:
      - start
      - --provider.name=docker
      - --server.metrics.enabled
    ports:
      - "127.0.0.1:10000:10000"
      - "100.117.222.10:10000:10000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
