services:
  db:
    image: mariadb:11
    container_name: limesurvey_db
    restart: unless-stopped
    env_file: [.env]
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PW}
      MARIADB_DATABASE: ${DB_NAME:-limesurvey}
      MARIADB_USER: ${DB_USER:-limesurvey}
      MARIADB_PASSWORD: ${DB_PW}
    volumes:
      - db:/var/lib/mysql
    labels:
      - "sablier.enable=true"
      - "sablier.group=limesurvey"

  limesurvey:
    image: martialblog/limesurvey:latest
    container_name: limesurvey
    restart: unless-stopped
    ports:
      - "9020:8080"
    env_file: [.env]
    environment:
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-limesurvey}
      DB_USERNAME: ${DB_USER:-limesurvey}
      DB_PASSWORD: ${DB_PW}
      ADMIN_USER: ${ADMIN_USER:-admin}
      ADMIN_NAME: ${ADMIN_USER:-admin}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@limesurvey.lab}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      BASE_URL: https://limesurvey.lab
      PUBLIC_URL: https://limesurvey.lab
    depends_on:
      - db
    volumes:
      - upload:/var/www/html/upload
    labels:
      - "sablier.enable=true"
      - "sablier.group=limesurvey"

volumes:
  db:
  upload:
