services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.26.0
    container_name: mealie
    restart: unless-stopped
    stop_grace_period: 60s
    ports:
      - "9001:9000"
    env_file: [.env]
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - mealie-data:/app/data/
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:9000/api/app/about"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 10s
    labels:
      - "sablier.enable=true"
      - "sablier.group=mealie"

volumes:
  mealie-data:
