services:
  server:
    image: woodpeckerci/woodpecker-server:v3
    container_name: woodpecker_server
    restart: unless-stopped
    ports:
      - "9011:8000"
    env_file: [.env]
    environment:
      WOODPECKER_OPEN: "false"
      WOODPECKER_GITHUB: "true"
    volumes:
      - data:/var/lib/woodpecker
    networks: [woodpecker-internal]
    labels:
      - "sablier.enable=true"
      - "sablier.group=woodpecker"

  agent:
    image: woodpeckerci/woodpecker-agent:v3
    container_name: woodpecker_agent
    restart: unless-stopped
    depends_on:
      - server
    env_file: [.env]
    environment:
      WOODPECKER_SERVER: server:9000
      WOODPECKER_MAX_WORKFLOWS: "2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: [woodpecker-internal]
    labels:
      - "sablier.enable=true"
      - "sablier.group=woodpecker"

volumes:
  data: {}

networks:
  woodpecker-internal: {}
